name: VPN Request Workflow

on:
  repository_dispatch:
    types: [vpn_request]

jobs:
  vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Extract VPN Request Data
        run: |
          echo "Extracting data from GitHub event..."
          
          # Extract JSON from payload
          EXTRA_DATA_JSON='${{ github.event.client_payload.extra_data }}'
          echo "Extracted JSON: $EXTRA_DATA_JSON"

          # Extract variables
          ipv4_cidr=$(echo "$EXTRA_DATA_JSON" | jq -r '.ipv4_cidr')
          customer_name="${{ github.event.client_payload.customer_name }}"

          echo "CIDR: $ipv4_cidr"
          echo "customer_name: $customer_name"

          # Export values for next steps
          echo "IPV4_CIDR=$ipv4_cidr" >> $GITHUB_ENV
          echo "customer_name=$customer_name" >> $GITHUB_ENV

      - name: Install Dependencies
        run: pip install boto3

      - name: Run CIDR Overlap Check
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:590184024707:tyfone-poc"
        run: python check_cidr.py
